### ISSUE TITLE
llnode install fail in ubuntu

### ISSUE THREAD

**Issue by langhuihui** [nodejs/llnode#128]
root@fed-QiTianM4360-N000:/home/fed/software# npm i -g llnode

> llnode@1.6.1 preinstall /usr/local/lib/node_modules/llnode
> node scripts/configure.js

Build dir is: /usr/local/lib/node_modules/llnode
bind: Invalid command `enable-meta-key'.
Checking for headers, version is 3.8
Installing llnode for /usr/bin/lldb, lldb version 3.8
Cloning lldb from release_38
child_process.js:614
    throw err;
    ^

Error: spawnSync git ENOENT
    at _errnoException (util.js:1041:11)
    at spawnSync (child_process.js:569:20)
    at Object.execFileSync (child_process.js:606:13)
    at Object.<anonymous> (/usr/local/lib/node_modules/llnode/scripts/configure.js:97:17)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Function.Module.runMain (module.js:609:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! llnode@1.6.1 preinstall: `node scripts/configure.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the llnode@1.6.1 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-08-31T07_45_11_681Z-debug.log

**Comment by indutny** [comment]
Sorry, the error could be more informative. You need to have `git` installed and available in your `PATH` in order to be able to run this tool.

**Comment by langhuihui** [comment]
thank u
