### ISSUE TITLE
test: errors running test/scan-test.js on Ubuntu 17.10

### ISSUE THREAD

**Issue by mmarchini** [nodejs/llnode#159]
I was beginning to write tests for #155, but I'm unable to run tests from `test/scan-test.js` on my machine. Not sure if I'm doing something wrong or if there's something wrong in my environment.

**Command**: `LLNODE_CORE=core LLNODE_NODE_EXE=$(which node) LLNODE_NO_RANGES=true npm test`
**Operating System**: Ubuntu 17.10
**LLDB**: v3.9 and v4.0
**Node**: v8.8.0
**Branch**: `master`

Those are the errors I'm getting (besides #150 which also happens sometimes)

```
# v8 findrefs and friends
ok 75 null
ok 76 Loaded core
========== lldb output ==========
(lldb) version
lldb version 3.9.1 ( revision )
=================================
not ok 77 Error: Test timeout in 20000 waiting for /lldb-/
  ---
    operator: error
    expected: |-
      undefined
    actual: |-
      [Error: Test timeout in 20000 waiting for /lldb-/]
    at: sess.wait (/home/mmarchini/workspace/sthima/llnode/test/scan-test.js:67:7)
    stack: |-
      Error: Test timeout in 20000 waiting for /lldb-/
          at Timeout.setTimeout [as _onTimeout] (/home/mmarchini/workspace/sthima/llnode/test/common.js:124:14)
          at ontimeout (timers.js:471:11)
          at Timer.unrefdHandle (timers.js:584:5)
  ...
========== lldb output ==========
(lldb) v8 findjsobjects
 Instances  Total Size Name
 ---------- ---------- ----
          1         24 AssertionError
          1         24 AsyncResource
          1         24 FastBuffer
          1         24 Instance
          1         24 Loader
          1         24 Memory
          1         24 ModuleJob
          1         24 ModuleMap
          1         24 Performance
          1         24 PerformanceObserver
          1         24 SafeMap
          1         24 SafePromise
          1         24 SafeSet
          1         24 Table
          1         24 TextDecoder
          1         24 TextEncoder
          1         24 TickObject
          1         24 URL
          1         24 URLContext
          1         24 URLSearchParams
          1         24 WebAssembly
          1         24 console
          1         32 (Object)
          1         96 Bar
          1        104 ImmediateList
          1        104 Stack
          1        112 Console
          2         48 (anonymous)
          2         48 process
          2         64 ChannelWrap
          2        120 Resolver
          2        128 PerformanceNodeTiming
          2        136 NextTickQueue
          2        152 AsyncHook
          2        200 PerformanceObserverEntryList
          2        208 WriteStream
          2        608 ReadableState
          2        640 WritableState
          3         72 NodeError
          3         96 TTY
          3        248 BufferList
          3        296 Module
          6        672 Foo
         11        352 ContextifyScript
         11        880 (ArrayBufferView)
         53       3392 NativeModule
        331      10592 (Array)
        610      34264 Object
       6871      71352 (String)
 ---------- ----------
       7954     125544
(lldb) version
lldb version 3.9.1 ( revision )
=================================
not ok 78 Error: Test timeout in 20000 waiting for /lldb-/
  ---
    operator: error
    expected: |-
      undefined
    actual: |-
      [Error: Test timeout in 20000 waiting for /lldb-/]
    at: sess.linesUntil (/home/mmarchini/workspace/sthima/llnode/test/scan-test.js:74:7)
    stack: |-
      Error: Test timeout in 20000 waiting for /lldb-/
          at Timeout.setTimeout [as _onTimeout] (/home/mmarchini/workspace/sthima/llnode/test/common.js:124:14)
          at ontimeout (timers.js:471:11)
          at Timer.unrefdHandle (timers.js:584:5)
  ...
/home/mmarchini/workspace/sthima/llnode/test/scan-test.js:75
    t.ok(/\d+ Zlib/.test(lines.join('\n')), 'Zlib should be in findjsobjects');
                               ^

TypeError: Cannot read property 'join' of undefined
    at sess.linesUntil (/home/mmarchini/workspace/sthima/llnode/test/scan-test.js:75:32)
    at Timeout.setTimeout [as _onTimeout] (/home/mmarchini/workspace/sthima/llnode/test/common.js:124:5)
    at ontimeout (timers.js:471:11)
    at Timer.unrefdHandle (timers.js:584:5)
npm ERR! Test failed.  See above for more details.
```

Any thoughts?

**Comment by joyeecheung** [comment]
Fix opened in https://github.com/nodejs/llnode/pull/160, I've tried it in my ubuntu xenial box.

**Comment by mmarchini** [comment]
@joyeecheung thanks for looking into it, your patch works here :)
