### ISSUE TITLE
installation issues on linux16.04

### ISSUE THREAD

**Issue by omerbn** [nodejs/llnode#184]
Hey, I'm getting the following error after running:
```
> npm install --lldb_exe=`which lldb-4.0` -g llnode --verbose


output:

npm verb cli [ '/usr/bin/node',
npm verb cli   '/usr/bin/npm',
npm verb cli   'install',
npm verb cli   '--lldb_exe=/usr/bin/lldb-4.0',
npm verb cli   '-g',
npm verb cli   'llnode',
npm verb cli   '--verbose' ]
npm info using npm@5.8.0
npm info using node@v8.11.1
npm verb npm-session 87897f6a74d4bc3d
npm http fetch GET 304 https://registry.npmjs.org/llnode 127ms (from cache)
npm verb correctMkdir /root/.npm/_locks correctMkdir not in flight; initializing
npm verb lock using /root/.npm/_locks/staging-a072192f34a17023.lock for /usr/lib/node_modules/.staging
npm info lifecycle llnode@1.7.0~preinstall: llnode@1.7.0

> llnode@1.7.0 preinstall /usr/lib/node_modules/llnode
> node scripts/configure.js

Build dir is: /usr/lib/node_modules/llnode
Installing llnode for /usr/bin/lldb-4.0, lldb version 4.0
Checking for headers, version is 4.0
fs.js:646
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: EACCES: permission denied, open 'config.gypi'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.writeFileSync (fs.js:1299:33)
    at writeConfig (/usr/lib/node_modules/llnode/scripts/configure.js:109:6)
    at main (/usr/lib/node_modules/llnode/scripts/configure.js:14:3)
    at Object.<anonymous> (/usr/lib/node_modules/llnode/scripts/configure.js:21:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
npm verb lifecycle llnode@1.7.0~preinstall: unsafe-perm in lifecycle false
npm verb lifecycle llnode@1.7.0~preinstall: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/usr/lib/node_modules/llnode/node_modules/.bin:/usr/lib/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
npm verb lifecycle llnode@1.7.0~preinstall: CWD: /usr/lib/node_modules/llnode
npm info lifecycle llnode@1.7.0~preinstall: Failed to exec preinstall script
npm verb unlock done using /root/.npm/_locks/staging-a072192f34a17023.lock for /usr/lib/node_modules/.staging
npm verb stack Error: llnode@1.7.0 preinstall: `node scripts/configure.js`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:283:16)
npm verb stack     at emitTwo (events.js:126:13)
npm verb stack     at EventEmitter.emit (events.js:214:7)
npm verb stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
npm verb stack     at emitTwo (events.js:126:13)
npm verb stack     at ChildProcess.emit (events.js:214:7)
npm verb stack     at maybeClose (internal/child_process.js:925:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
npm verb pkgid llnode@1.7.0
npm verb cwd /home/ubuntu
npm verb Linux 4.4.0-1041-aws
npm verb argv "/usr/bin/node" "/usr/bin/npm" "install" "--lldb_exe=/usr/bin/lldb-4.0" "-g" "llnode" "--verbose"
npm verb node v8.11.1
npm verb npm  v5.8.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! llnode@1.7.0 preinstall: `node scripts/configure.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the llnode@1.7.0 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm verb exit [ 1, true ]

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-04-02T10_00_31_781Z-debug.log
root@ip-10-1-1-241:/home/ubuntu# npm install --lldb_exe=`which lldb-4.0` -g llnode --verbose^C
root@ip-10-1-1-241:/home/ubuntu# vi /root/.npm/_logs/2018-04-02T09_32_10_239Z-debug.log
53 verbose stack     at EventEmitter.emit (events.js:214:7)
53 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
53 verbose stack     at emitTwo (events.js:126:13)
53 verbose stack     at ChildProcess.emit (events.js:214:7)
53 verbose stack     at maybeClose (internal/child_process.js:925:16)
53 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
54 verbose pkgid llnode@1.7.0
55 verbose cwd /root
56 verbose Linux 4.4.0-1041-aws
57 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "--lldb_exe=/usr/bin/lldb-4.0" "-g" "llnode"
58 verbose node v8.11.1
59 verbose npm  v5.8.0
60 error code ELIFECYCLE
61 error errno 1
62 error llnode@1.7.0 preinstall: `node scripts/configure.js`
62 error Exit status 1
63 error Failed at the llnode@1.7.0 preinstall script.
63 error This is probably not a problem with npm. There is likely additional logging output above.
64 verbose exit [ 1, true ]

**Comment by bnoordhuis** [comment]
You're trying to install to `/usr/lib` so you'll need the appropriate privileges (root).  Note that npm drops privileges unless you specify `--unsafe-perms`.

**Comment by omerbn** [comment]
Thanks,

The error persists when running:

> sudo npm install --lldb_exe=`which lldb-4.0` -g llnode --unsafe-perms

**Comment by joyeecheung** [comment]
Hi, how did you install your node and npm? Can you try the options provided by [the documentation of npm](https://docs.npmjs.com/getting-started/fixing-npm-permissions)?

**Comment by omerbn** [comment]
I have followed the 2nd option in that document.
I am still getting this error.

What am I doing wrong?

**Comment by No9** [comment]
Hi @omerbn 
I've tested this on an ubuntu 16.04 also with option 2 from the npm permissions options Joyee gave and got no problems.

I noticed in my log that it selects the build directory to be on the path that is relative to the prefix I gave to the npm configuration where as the log above is still pointing at `Build dir is: /usr/lib/node_modules/llnode`
Can you confirm the prefix for the user you are trying to install under by running the following commands and providing output: 
```
$ whoami
anton
$ npm config get prefix
/home/anton/.local
```

**Comment by joyeecheung** [comment]
@omerbn Do your user own the directory `/home/ubuntu/.npm-global`? What's your installation log after configuring your npm prefix?

**Comment by joyeecheung** [comment]
Also, if you simply want to use llnode, you don't have to install it globally. `git clone` this repo then `npm install` there would build the plugin, then you can load the plugin into lldb via 2, 3, or 4 in https://github.com/nodejs/llnode#loading-the-llnode-plugin

**Comment by mmarchini** [comment]
`npx llnode` usually works as well.

**Comment by omerbn** [comment]
I've managed to resolve the issue by installing node-gyp. 
I didn't see this missing-package while running in root mode.

Thank you guys!

**Comment by joyeecheung** [comment]
@omerbn Kind of confused why reinstalling node-gyp fixed the permission issues in the preinstall hook, but glad to hear that it worked out. I'll close this now, thanks.

**Comment by omerbn** [comment]
I'm confused too, but it worked. ⭕️ 

Thank you guys for the help!

**Comment by eladnava** [comment]
Make sure to change the `npm` global package installation directory as follows:
https://docs.npmjs.com/getting-started/fixing-npm-permissions
