### ISSUE TITLE
Tests fail on Linux if gcore is not installed (with misleading message)

### ISSUE THREAD

**Issue by mmarchini** [nodejs/llnode#249]
Message was really not helpful:

```
# v8 findrefs and friends
ok 79 null
ok 80 Saved core
ok 81 null
ok 82 Loaded core
ok 83 null
not ok 84 Class should be in findjsobjects
  ---
    operator: ok
    expected: true
    actual:   false
    at: sess.linesUntil (/home/mmarchini/llnode/test/plugin/scan-test.js:37:7)
    stack: |-
      Error: Class should be in findjsobjects
          at Test.assert [as _assert] (/home/mmarchini/llnode/node_modules/tape/lib/test.js:224:54)
          at Test.bound [as _assert] (/home/mmarchini/llnode/node_modules/tape/lib/test.js:76:32)
          at Test.assert (/home/mmarchini/llnode/node_modules/tape/lib/test.js:342:10)
          at Test.bound [as ok] (/home/mmarchini/llnode/node_modules/tape/lib/test.js:76:32)
          at sess.linesUntil (/home/mmarchini/llnode/test/plugin/scan-test.js:37:7)
          at SessionOutput.onLine (/home/mmarchini/llnode/test/common.js:113:5)
          at emitOne (events.js:96:13)
          at SessionOutput.emit (events.js:188:7)
          at Socket.SessionOutput.stream.on (/home/mmarchini/llnode/test/common.js:63:14)
          at emitOne (events.js:96:13)
  ...
ok 85 null
not ok 86 "Class: x, y, hashmap" should be in findjsobjects -d
  ---
    operator: ok
    expected: true
    actual:   false
    at: sess.linesUntil (/home/mmarchini/llnode/test/plugin/scan-test.js:46:7)
    stack: |-
      Error: "Class: x, y, hashmap" should be in findjsobjects -d
          at Test.assert [as _assert] (/home/mmarchini/llnode/node_modules/tape/lib/test.js:224:54)
          at Test.bound [as _assert] (/home/mmarchini/llnode/node_modules/tape/lib/test.js:76:32)
          at Test.assert (/home/mmarchini/llnode/node_modules/tape/lib/test.js:342:10)
          at Test.bound [as ok] (/home/mmarchini/llnode/node_modules/tape/lib/test.js:76:32)
          at sess.linesUntil (/home/mmarchini/llnode/test/plugin/scan-test.js:46:7)
          at SessionOutput.onLine (/home/mmarchini/llnode/test/common.js:113:5)
          at emitOne (events.js:96:13)
          at SessionOutput.emit (events.js:188:7)
          at Socket.SessionOutput.stream.on (/home/mmarchini/llnode/test/common.js:63:14)
          at emitOne (events.js:96:13)
  ...
ok 87 null
/home/mmarchini/llnode/test/plugin/scan-test.js:57
    t.ok((lines.join('\n').match(/<Object: Class_B>/g)).length == 10, 'Should show 10 instances');
                                                       ^

TypeError: Cannot read property 'length' of null
    at sess.linesUntil (/home/mmarchini/llnode/test/plugin/scan-test.js:57:56)
    at SessionOutput.onLine (/home/mmarchini/llnode/test/common.js:113:5)
    at emitOne (events.js:96:13)
    at SessionOutput.emit (events.js:188:7)
    at Socket.SessionOutput.stream.on (/home/mmarchini/llnode/test/common.js:63:14)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:559:20)
```

We should check if gcore is installed and skip otherwise.

**Comment by Drieger** [comment]
@mmarchini how can I trigger the error? I'm trying to reproduce it, but even after moving `gcore` 

```bash
-bash: /usr/bin/gcore: No such file or directory
```
 all tests passed

```bash
...
1..126
# tests 126
# pass  126

# ok
```

**Comment by mmarchini** [comment]
We don't use gcore on tests anymore
