### ISSUE TITLE
Flaky findrefs test on Node.js 10

### ISSUE THREAD

**Issue by mmarchini** [nodejs/llnode#278]
Has been happening a lot lately:

```
not ok 127 Should find reference #4
  ---
    operator: ok
    expected: true
    actual:   false
    at: sess.hasSymbol (/Users/travis/build/nodejs/llnode/test/plugin/scan-test.js:183:11)
    stack: |-
      Error: Should find reference #4
          at Test.assert [as _assert] (/Users/travis/build/nodejs/llnode/node_modules/tape/lib/test.js:226:54)
          at Test.bound [as _assert] (/Users/travis/build/nodejs/llnode/node_modules/tape/lib/test.js:77:32)
          at Test.assert (/Users/travis/build/nodejs/llnode/node_modules/tape/lib/test.js:344:10)
          at Test.bound [as ok] (/Users/travis/build/nodejs/llnode/node_modules/tape/lib/test.js:77:32)
          at sess.hasSymbol (/Users/travis/build/nodejs/llnode/test/plugin/scan-test.js:183:11)
          at linesUntil (/Users/travis/build/nodejs/llnode/test/common.js:318:7)
          at SessionOutput.onLine (/Users/travis/build/nodejs/llnode/test/common.js:113:5)
          at SessionOutput.emit (events.js:189:13)
          at Socket.SessionOutput.stream.on (/Users/travis/build/nodejs/llnode/test/common.js:63:14)
          at Socket.emit (events.js:189:13)
  ...
```

**Comment by mmarchini** [comment]
Not a flaky test, this is actually a bug with (apparently) `findrefs`.
