### ISSUE TITLE
installation fails (macOS Catalina)

### ISSUE THREAD

**Issue by hugebdu** [nodejs/llnode#376]
- node v12.19.0 (nvm managed)
- npm v6.14.8

running `sudo npm install -g llnode` fails with

```
> llnode@3.2.0 preinstall /Users/daniels/.nvm/versions/node/v12.19.0/lib/node_modules/llnode
> node scripts/configure.js

Build dir is: /Users/daniels/.nvm/versions/node/v12.19.0/lib/node_modules/llnode
Using lldb executable lldb

Looking for llvm-config...
No llvm-config found

Reading lldb version...
Deduced lldb version from Xcode version: Xcode 12.1 -> lldb 3.9
Installing llnode for lldb, lldb version 3.9

Looking for headers for lldb 3.9...
Could not find the headers, will download them later

Looking for shared libraries for lldb 3.9...
Could not find the shared libraries
llnode will be linked to the LLDB shared framework from the Xcode installation

Cloning lldb release_39 into /Users/user/.nvm/versions/node/v12.19.0/lib/node_modules/llnode/lldb-3.9
fatal: could not create work tree dir '/Users/user/.nvm/versions/node/v12.19.0/lib/node_modules/llnode/lldb-3.9': Permission denied
child_process.js:656
    throw err;
    ^

Error: Command failed: git clone --depth 1 --branch release_39 https://github.com/llvm-mirror/lldb.git /Users/daniels/.nvm/versions/node/v12.19.0/lib/node_modules/llnode/lldb-3.9
    at checkExecSyncError (child_process.js:635:11)
    at Object.execFileSync (child_process.js:653:15)
    at Object.cloneHeaders (/Users/daniels/.nvm/versions/node/v12.19.0/lib/node_modules/llnode/scripts/lldb.js:47:19)
```

**Comment by No9** [comment]
As per the install instructions 
Never install llnode with sudo
https://github.com/nodejs/llnode/blob/master/README.md#quick-start
I’m not an nvm user but it looks like it’s trying to do the right thing anyway by installing it into your user directories so the install without sudo should “just work”
