### ISSUE TITLE
js api is probably broken

### ISSUE THREAD

**Issue by rifler** [nodejs/llnode#388]
llnode - 3.2.0
node - 12.19.0
OS - linux

stack trace on require
```
> require('llnode')
Uncaught Error: Could not locate the bindings file. Tried:
 → /home/rifler/node_modules/llnode/build/addon.node
 → /home/rifler/node_modules/llnode/build/Debug/addon.node
 → /home/rifler/node_modules/llnode/build/Release/addon.node
 → /home/rifler/node_modules/llnode/out/Debug/addon.node
 → /home/rifler/node_modules/llnode/Debug/addon.node
 → /home/rifler/node_modules/llnode/out/Release/addon.node
 → /home/rifler/node_modules/llnode/Release/addon.node
 → /home/rifler/node_modules/llnode/build/default/addon.node
 → /home/rifler/node_modules/llnode/compiled/12.19.0/linux/x64/addon.node
 → /home/rifler/node_modules/llnode/addon-build/release/install-root/addon.node
 → /home/rifler/node_modules/llnode/addon-build/debug/install-root/addon.node
 → /home/rifler/node_modules/llnode/addon-build/default/install-root/addon.node
 → /home/rifler/node_modules/llnode/lib/binding/node-v72-linux-x64/addon.node
    at bindings (/home/rifler/node_modules/bindings/bindings.js:126:9)
    at Object.<anonymous> (/home/rifler/node_modules/llnode/index.js:7:24)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (internal/modules/cjs/helpers.js:74:18) {
  tries: [
    '/home/rifler/node_modules/llnode/build/addon.node',
    '/home/rifler/node_modules/llnode/build/Debug/addon.node',
    '/home/rifler/node_modules/llnode/build/Release/addon.node',
    '/home/rifler/node_modules/llnode/out/Debug/addon.node',
    '/home/rifler/node_modules/llnode/Debug/addon.node',
    '/home/rifler/node_modules/llnode/out/Release/addon.node',
    '/home/rifler/node_modules/llnode/Release/addon.node',
    '/home/rifler/node_modules/llnode/build/default/addon.node',
    '/home/rifler/node_modules/llnode/compiled/12.19.0/linux/x64/addon.node',
    '/home/rifler/node_modules/llnode/addon-build/release/install-root/addon.node',
    '/home/rifler/node_modules/llnode/addon-build/debug/install-root/addon.node',
    '/home/rifler/node_modules/llnode/addon-build/default/install-root/addon.node',
    '/home/rifler/node_modules/llnode/lib/binding/node-v72-linux-x64/addon.node'
  ]
}
```

**Comment by No9** [comment]
The API requires the additional flag `--llnode_build_addon=true` to be set for the npm install command.
e.g.  npm install llnode --llnode_build_addon=true
